name:                the-bipartite-mind
version:             1.0.0.0
# github:              "coarchive/the-bipartite-mind"
license:             BSD3
author:              "coalpha coalpha"
# maintainer:          "example@example.com"
copyright:           "2023 coalpha"

dependencies:
- base >= 4.7 && < 5
- TernaryTrees

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


executables:
  the-bipartite-mind-exe:
    main: the-bipartite-mind.hs
    # source-dirs: src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
