resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/12.yaml

packages:
- .

extra-deps:
- TernaryTrees-0.2.0.2@sha256:45c18fdcf93bb162da28f88852976ac8f3c1fba1a4ba623e05032b048bfd2659,2353
