words_txt = open("words.txt", "r")
words_h = open("words.h", "w")

word_count = 0
words_h.write("// generated by words.py\n")
words_h.write("char const words[][5] = {\n")

for word in words_txt:
   word = word.strip()
   non_null_terminated_string = ", ".join([f"'{char}'" for char in word])
   words_h.write(f"   {{{non_null_terminated_string}}},\n")
   word_count += 1

words_h.write("};\n\n")
words_h.write(f"size_t word_count = {word_count};\n")
